# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'dreamers' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for dreamers

  

  target 'dreamersTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'dreamers-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for dreamers-tvOS

  target 'dreamers-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
